apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scorpio.fullname" . }}-properties
  labels:
    {{- include "scorpio.labels" . | nindent 4 }}
data:
  ATCONTEXT_URL: http://{{ include "scorpio.fullname" . }}:{{ .Values.service.port }}/ngsi-ld/v1/jsonldContexts/
  NGSILD_CORECONTEXT: {{ .Values.config.ngsildCoreContext | quote }}
  QUARKUS_LOG_LEVEL: {{ .Values.config.quarkusLogLevel | quote }}
  QUARKUS_VERTX_EVENT-LOOPS-POOL-SIZE: {{ .Values.config.quarkusVertxEventLoopsPoolSize | quote }}
  SCORPIO_DIRECTDB: {{ .Values.config.scorpioDirectDb | quote }}
  SCORPIO_HISTORY_AUTORECORDING: {{ .Values.config.scorpioHistoryAutorecording | quote }}
  SCORPIO_HISTORY_MAX_LIMIT: {{ .Values.config.scorpioHistoryMaxLimit | int | quote }}
  SCORPIO_HISTORY_DEFAULT_LIMIT: {{ .Values.config.scorpioHistoryDefaultLimit | int | quote }}
  SCORPIO_FEDUPDATERATE: {{ .Values.config.scorpioFedupdaterate | quote }}
  SCORPIO_SUBSCRIPTION_CHECKINTERVAL: {{ .Values.config.scorpioSubscriptionCheckInterval | quote }}
