{{- if .Values.rabbitmq.enabled }}
{{- $rabbitmqHostname := default (randAlphaNum 16) .Values.rabbitmq.config.hostname | b64enc | quote }}
{{- $rabbitmqPassword := default (randAlphaNum 16) .Values.rabbitmq.config.password | b64enc | quote }}
{{- $rabbitmqUsername := default (randAlphaNum 16) .Values.rabbitmq.config.username | b64enc | quote }}

{{- if .Values.rabbitmq.existingPasswordSecret }}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace .Values.rabbitmq.existingPasswordSecret) }}
{{- if $existingSecret }}
{{- $rabbitmqPassword = index $existingSecret.data "rabbitmq-password"}}
{{- end -}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scorpio.fullname" . }}-rabbitmq
  labels:
    {{- include "scorpio.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  CAMEL_COMPONENT_RABBITMQ_HOSTNAME: {{ $rabbitmqHostname }}
  CAMEL_COMPONENT_RABBITMQ_PASSWORD: {{ $rabbitmqPassword }}
  CAMEL_COMPONENT_RABBITMQ_USERNAME: {{ $rabbitmqUsername }}
{{- end }}