apiVersion: v1
kind: Service
metadata:
  name: {{ include "scorpio.fullname" . }}
  labels:
    {{- include "scorpio.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "scorpio.fullname" . }}-aio
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "scorpio.selectorLabels" . | nindent 4 }}
